/**
 * @file Router.h
 * @brief Router class declaration
 * 
 * Copyright (c) 2025 Hüseyin Karakaya (https://github.com/karakayahuseyin)
 * Licensed under the MIT License. Part of the Revak project.
 */

#pragma once

#include "Handler.h"
#include "Response.h"
#include "Request.h"

#include <vector>
#include <string>

namespace revak {

/** 
 * @struct Route
 * @brief Represents a single route with method, path, and handler
 */
struct Route
{
  std::string method;
  std::string path;
  Handler handler;
};

/**
 * @class Router
 * @brief Manages routing of HTTP requests to their corresponding handlers
 */
class Router {
public:
  /**
   * @brief Add a route to the router
   * @param method HTTP method (e.g., "GET", "POST")
   * @param path URL path (e.g., "/home")
   * @param handler Handler function to process the request
   * @return true if the route was added successfully, false otherwise
   */
  bool AddRoute(const std::string& method, const std::string& path, Handler handler);

  /**
   * @brief Dispatch a request to the appropriate handler based on method and path
   * @param request The incoming HTTP request
   * @return The response generated by the handler
   */
  Response Dispatch(const Request& request);

private: 
  /** 
   * @brief Map to store routes with method and path as keys
   * The outer map's key is the HTTP method, and the inner map's key is the URL path.
   */
  std::map<std::string, std::map<std::string, Handler>> routes_;
};

}  // namespace revak