/**
 * @file Router.h
 * @brief Router class declaration
 * 
 * Copyright (c) 2025 Hüseyin Karakaya (https://github.com/karakayahuseyin)
 * Licensed under the MIT License. Part of the Revak project.
 */

#pragma once

#include "Handler.h"
#include "Response.h"
#include "Request.h"

#include <vector>
#include <string>

namespace revak {

struct Route
{
  std::string method;
  std::string path;
  Handler handler;
};


class Router {
public:
  /// @brief Add a new route to the router
  /// @param method method (e.g., GET, POST)
  /// @param path request path 
  /// @param handler handler function
  void AddRoute(const std::string& method, const std::string& path, Handler handler);

  /// @brief Dispatch the request to the appropriate handler
  /// @param request Incoming request
  /// @return Response generated by the handler
  Response Dispatch(Request& request);

private: 
  // Tech debt: Change to more efficient structure:
  // std::map<std::string, std::map<std::string, Handler>> routes_; // <method, <path, handler>>
  std::vector<Route> routes_;
};

}  // namespace revak